In [ ]:
A = [[1, 4, 5, 12], 
    [-5, -8, 9, 0],
    [-6, 7, 1, 9]]

print("A =", A) 
print("A[0] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, -8, 9, 0], [-6, 7, 1, 9]]
A[0] = [-5, -8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 1]


In [ ]:
import numpy as np

a = np.array([10, 20, 30])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

[10 20 30]
<class 'numpy.ndarray'>


In [7]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2.2, 3.3], [3.3, 4.4, 5.5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[1.1 2.2 3.3]
 [3.3 4.4 5.5]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [8]:
zeros_array = np.zeros( (2, 3) )
print(zeros_array)


ones_array = np.ones( (1, 5), dtype=np.int32 ) 
print(ones_array)      

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]]


In [10]:
A = np.arange(8)
print('A =', A)

B = np.arange(12).reshape(3,4)
print('B =', B)

A = [0 1 2 3 4 5 6 7]
B = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


In [15]:
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(A)
print(B)

print(C)

[[ 3  6  7]
 [ 5 -3  0]]
[[ 1  1]
 [ 2  1]
 [ 3 -3]]
[[ 36 -12]
 [ -1   2]]


In [ ]:
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

In [16]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])  # two rows, four columns
print(A[:1,])  # first row, all columns
print(A[:,2])  # all rows, second column
print(A[:, 2:5])  # all rows, third to the fifth column



[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]
[ 5  9 11]
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
